const fsHelpers = require('../utils/fsHelpers');
const ui = require('../ui/output');
const { rel } = require('./helpers');

const SRC_ENTRY = '/src/generated/prisma';
const ROOT_ENTRY = '/generated/prisma';

function entriesFor(ctx) {
    // `prisma init` writes /generated/prisma by default; in "src" mode that
    // default location is a stale leftover we strip, and vice versa.
    return ctx.clientOutput === 'root'
        ? { wanted: ROOT_ENTRY, stale: SRC_ENTRY }
        : { wanted: SRC_ENTRY, stale: ROOT_ENTRY };
}

function hasEntry(source, entry) {
    return source.split(/\r?\n/).some((line) => line.trim() === entry);
}

function addEntry(source, wanted, stale) {
    const lines = source.split(/\r?\n/).filter((line) => line.trim() !== stale);
    while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
    if (lines.length) lines.push('');
    lines.push('# Prisma Client (generated by "prisma generate")', wanted, '');
    return lines.join('\n');
}

module.exports = {
    id: 'gitignore',
    title: 'Ignore the generated client',

    async plan(ctx) {
        const file = rel(ctx, ctx.paths.gitignore);
        const { wanted, stale } = entriesFor(ctx);
        if (await fsHelpers.exists(ctx.paths.gitignore)) {
            const source = await fsHelpers.readFile(ctx.paths.gitignore);
            if (hasEntry(source, wanted)) {
                return { entries: [{ kind: 'skip', label: file, reason: `already ignores ${wanted}` }] };
            }
            return { entries: [{ kind: 'modify', label: `${file} (add ${wanted})` }] };
        }
        return { entries: [{ kind: 'create', label: `${file} (with ${wanted})` }] };
    },

    async run(ctx) {
        const file = rel(ctx, ctx.paths.gitignore);
        const exists = await fsHelpers.exists(ctx.paths.gitignore);
        const { wanted, stale } = entriesFor(ctx);
        const source = exists ? await fsHelpers.readFile(ctx.paths.gitignore) : '';

        // Re-check at run time: `prisma init` may have edited the file in between.
        if (hasEntry(source, wanted)) {
            ui.skip(`${file} already ignores ${wanted}`);
            return { status: 'skipped' };
        }

        await fsHelpers.writeFile(ctx.paths.gitignore, addEntry(source, wanted, stale));
        ui.success(`Added ${wanted} to ${file}`);
        return { files: [{ kind: exists ? 'modify' : 'create', path: file }] };
    },
};

module.exports.addEntry = addEntry;
module.exports.SRC_ENTRY = SRC_ENTRY;
module.exports.ROOT_ENTRY = ROOT_ENTRY;
