const fsHelpers = require('../utils/fsHelpers');
const ui = require('../ui/output');
const { rel } = require('./helpers');

const GENERATED_ENTRY = '/src/generated/prisma';
// Added by `prisma init` for its default output location, which we don't use.
const STALE_ENTRY = '/generated/prisma';

function hasEntry(source) {
    return source.split(/\r?\n/).some((line) => line.trim() === GENERATED_ENTRY);
}

function addEntry(source) {
    const lines = source.split(/\r?\n/).filter((line) => line.trim() !== STALE_ENTRY);
    while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
    if (lines.length) lines.push('');
    lines.push('# Prisma Client (generated by "prisma generate")', GENERATED_ENTRY, '');
    return lines.join('\n');
}

module.exports = {
    id: 'gitignore',
    title: 'Ignore the generated client',

    async plan(ctx) {
        const file = rel(ctx, ctx.paths.gitignore);
        if (await fsHelpers.exists(ctx.paths.gitignore)) {
            const source = await fsHelpers.readFile(ctx.paths.gitignore);
            if (hasEntry(source)) {
                return { entries: [{ kind: 'skip', label: file, reason: `already ignores ${GENERATED_ENTRY}` }] };
            }
            return { entries: [{ kind: 'modify', label: `${file} (add ${GENERATED_ENTRY})` }] };
        }
        return { entries: [{ kind: 'create', label: `${file} (with ${GENERATED_ENTRY})` }] };
    },

    async run(ctx) {
        const file = rel(ctx, ctx.paths.gitignore);
        const exists = await fsHelpers.exists(ctx.paths.gitignore);
        const source = exists ? await fsHelpers.readFile(ctx.paths.gitignore) : '';

        // Re-check at run time: `prisma init` may have edited the file in between.
        if (hasEntry(source)) {
            ui.skip(`${file} already ignores ${GENERATED_ENTRY}`);
            return { status: 'skipped' };
        }

        await fsHelpers.writeFile(ctx.paths.gitignore, addEntry(source));
        ui.success(`Added ${GENERATED_ENTRY} to ${file}`);
        return { files: [{ kind: exists ? 'modify' : 'create', path: file }] };
    },
};

module.exports.addEntry = addEntry;
module.exports.GENERATED_ENTRY = GENERATED_ENTRY;
